[package]
name = "myos"
version = "0.1.0"
authors = ["Adam Short <ashort11@vols.utk.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[dependencies]
